blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discord
    url: https://discord.gg/someengineering
    about: Chat with other users and the development team
  - name: ðŸ“„ Documentation
    url: https://cloud2sql.com/docs
    about: Read and search documentation
